apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-template
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: dev
        filepath: values-dev.yaml 
      - namespace: test
        filepath: values-prod.yaml 
      - namespace: uat
        filepath: values-uat.yaml

  template:
    metadata:
      name: 'helm-template-{{namespace}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: 'https://github.com/speedygamer12/helm-template'
        targetRevision: HEAD
        path: helm-template                
        helm:
          valueFiles:
            - '{{filepath}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'default'