apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-template
  namespace: default
spec:
  generators:
  - list:
      elements:
      - namespace: dev
        url: https://kubernetes.default.svc
      - namespace: test
        url: https://kubernetes.default.svc
      - namespace: uat
        url: https://kubernetes.default.svc

  template:
    metadata:
      name: 'helm-template-{{namespace}}'
    spec:
      project: default
      syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
      source:
        repoURL: 'https://github.com/speedygamer12/helm-template'
        targetRevision: HEAD
        path: helm-template                
        helm:
          valueFiles:
            - 'values-{{namespace}}.yml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'