apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-template
  namespace: name: '{{"{{"}}namespace{{"}}"}}'
spec:
  generators:
  - list:
      elements:
      - namespace: dev
        url: https://kubernetes.default.svc
      - namespace: test
        url: https://kubernetes.default.svc
      - namespace: uat
        url: https://kubernetes.default.svc

  template:
    metadata:
      name: argocd
    spec:
      project: default
      source:
        path: helm-template
        repoURL: https://github.com/speedygamer12/helm-template.git
        targetRevision: HEAD
        helm:
          valueFiles:
            - values.yaml
            - values-{{"{{"}}namespace{{"}}"}}.yaml
      destination:
        server: '{{"{{"}}url{{"}}"}}'
        namespace: '{{"{{"}}namespace{{"}}"}}'